use std::fs;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

use byteser::ByteSerializable;

use super::node_identity::NodeIdentity;

const IDENTITY_FILE: &str = "identity.bin";
const NODE_CERT_FILE: &str = "node-cert.pem";
const NODE_KEY_FILE: &str = "node-key.pem";
const ISSUER_CERT_FILE: &str = "issuer-cert.pem";

/// Filesystem-backed identity vault.
///
/// The vault owns one directory per node and stores:
/// - `identity.bin`    – node identity serialized as raw bytes
/// - `node-cert.pem`   – the node's public certificate / signed credential
/// - `node-key.pem`    – the node's private key
/// - `issuer-cert.pem` – the issuer's certificate (for non-bootstrap nodes)
#[derive(Debug, Clone)]
pub struct IdentityVault {
    root: PathBuf,
}

impl IdentityVault {
    /// Opens (but does not create) the vault at `root`.
    pub fn new<P: AsRef<Path>>(root: P) -> Self {
        Self {
            root: root.as_ref().to_path_buf(),
        }
    }

    /// Returns the vault root directory.
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Creates the vault directory tree if it does not exist.
    pub fn ensure_root(&self) -> Result<(), Box<dyn std::error::Error>> {
        fs::create_dir_all(&self.root)?;
        Ok(())
    }

    /// Path to the node identity metadata file.
    pub fn identity_path(&self) -> PathBuf {
        self.root.join(IDENTITY_FILE)
    }

    /// Path to the node certificate file.
    pub fn node_cert_path(&self) -> PathBuf {
        self.root.join(NODE_CERT_FILE)
    }

    /// Path to the node private key file.
    pub fn node_key_path(&self) -> PathBuf {
        self.root.join(NODE_KEY_FILE)
    }

    /// Path to the issuer certificate file.
    pub fn issuer_cert_path(&self) -> PathBuf {
        self.root.join(ISSUER_CERT_FILE)
    }

    /// Persists a `NodeIdentity` to the vault as raw bytes.
    ///
    /// The identity is serialized using `ByteSerializable` and stored in
    /// `identity.bin`. The certificate and key files are expected to already
    /// exist in the working directory (generated by `super::certs::create_certificates`)
    /// and are copied into the vault.
    pub fn save(&self, identity: &NodeIdentity) -> Result<(), Box<dyn std::error::Error>> {
        self.ensure_root()?;

        let mut bytes = Vec::new();
        identity.byte_serialize(&mut bytes);

        let mut file = fs::File::create(self.identity_path())?;
        file.write_all(&bytes)?;
        file.sync_all()?;

        fs::copy(NODE_CERT_FILE, self.node_cert_path())?;
        fs::copy(NODE_KEY_FILE, self.node_key_path())?;

        Ok(())
    }

    /// Loads a `NodeIdentity` from the vault.
    ///
    /// Returns an error if the vault directory or `identity.bin` is missing,
    /// or if the stored bytes cannot be deserialized.
    pub fn load_identity(&self) -> Result<NodeIdentity, Box<dyn std::error::Error>> {
        let path = self.identity_path();
        let mut file = fs::File::open(&path)
            .map_err(|e| format!("failed to open identity vault at {}: {}", path.display(), e))?;
        let mut bytes = Vec::new();
        file.read_to_end(&mut bytes)?;

        let mut slice: &[u8] = &bytes;
        let identity = NodeIdentity::byte_deserialize(&mut slice)
            .map_err(|e| format!("failed to deserialize identity: {}", e))?;
        Ok(identity)
    }

    /// Checks whether the vault already contains a persisted identity.
    pub fn exists(&self) -> bool {
        self.identity_path().is_file() && self.node_cert_path().is_file() && self.node_key_path().is_file()
    }

    /// Copies the certificate and key files from the vault into the current
    /// working directory so that TLS code that expects `node-cert.pem` and
    /// `node-key.pem` in the working directory can find them.
    pub fn copy_certs_to_working_dir(&self) -> Result<(), Box<dyn std::error::Error>> {
        fs::copy(self.node_cert_path(), NODE_CERT_FILE)?;
        fs::copy(self.node_key_path(), NODE_KEY_FILE)?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use super::super::node_identity::IssuerIdentity;
    use std::env;
    use std::fs;
    use uuid::Uuid;

    #[test]
    fn vault_roundtrip() {
        let tmp = env::temp_dir().join(format!("trench-vault-test-{}", Uuid::new_v4()));
        let vault = IdentityVault::new(&tmp);

        let issuer = IssuerIdentity {
            id: Uuid::new_v4(),
            fingerprint: "issuer-fp".to_string(),
            address: "localhost:9000".to_string(),
            region: "ap-south-1".to_string(),
            status: "active".to_string(),
            issuer_bootstraped: true,
        };

        let identity = NodeIdentity {
            id: Uuid::new_v4(),
            region: "ap-south-1".to_string(),
            address: "localhost:8000".to_string(),
            status: "active".to_string(),
            issuer,
            fingerprint: "node-fp".to_string(),
            bootstraped: true,
        };

        fs::write(NODE_CERT_FILE, b"dummy cert").unwrap();
        fs::write(NODE_KEY_FILE, b"dummy key").unwrap();

        vault.save(&identity).unwrap();
        assert!(vault.exists());

        let loaded = vault.load_identity().unwrap();
        assert_eq!(loaded.id, identity.id);
        assert_eq!(loaded.fingerprint, identity.fingerprint);
        assert_eq!(loaded.issuer.id, identity.issuer.id);

        let cert = fs::read_to_string(vault.node_cert_path()).unwrap();
        assert_eq!(cert, "dummy cert");

        fs::remove_dir_all(&tmp).unwrap();
        fs::remove_file(NODE_CERT_FILE).ok();
        fs::remove_file(NODE_KEY_FILE).ok();
    }
}
